########################################
# Base image
########################################

FROM ubuntu:22.04 as base
SHELL ["/bin/bash", "-c"]
ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND="noninteractive"
WORKDIR /fuzzer
USER root

RUN apt update
RUN apt install -y --no-install-recommends git

COPY ./stub/packages/22.04/* /opt/packages/
RUN dpkg -i /opt/packages/*; \
	apt install -y -f && \
	rm -rf /opt/packages

COPY ./stub/get-pip.py ./
RUN python3.7 ./get-pip.py && \
    rm get-pip.py

RUN python3.7 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements*.txt ./
RUN pip3 install -r requirements-prod.txt

########################################
# Release image
########################################

FROM ubuntu:22.04
SHELL ["/bin/bash", "-c"]
ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND="noninteractive"
WORKDIR /fuzzer

ARG ENVIRONMENT=dev
ENV ENVIRONMENT=$ENVIRONMENT

RUN apt update && apt install -y ca-certificates
COPY ./stub/packages/22.04/* /opt/packages/
RUN dpkg -i /opt/packages/*; \
	apt install -y -f && \
	rm -rf /opt/packages

COPY agent ./agent
COPY logging.yaml ./
COPY --from=base /opt/venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"
CMD python3 -m agent